### ISSUE TITLE
Month starts from 0 rather than 1

### ISSUE THREAD

**Issue by NikeshNiraula** [sprajwal078/angular-nepali-datepicker#19]
![image](https://user-images.githubusercontent.com/54625724/107729440-07f46800-6d19-11eb-9b12-6c27ea3472fc.png)

**Comment by sprajwal078** [comment]
Hi @NikeshNiraula. Thanks for pointing out the bug. I'll take a look into it and release a fix asap

**Comment by NikeshNiraula** [comment]
@sprajwal078 Thank you for the response. Hope you fix it soon.

**Comment by sprajwal078** [comment]
@NikeshNiraula After some research, it turns out the month starting with 0 is a JS thing. Please refer to this [Stack Overflow question ](https://stackoverflow.com/questions/2552483/why-does-the-month-argument-range-from-0-to-11-in-javascripts-date-constructor)

I suggest you use the formatter directive and format your value according to your need. Here's an example

```ts
formatter: DateFormatter = (date) => {
  return `year: ${ date.year }, month: ${ date.month + 1 }, day: ${ date.day }`;
}
```

```html
<np-datepicker
  [(ngModel)]="date"
  [dateFormatter]="formatter">
</np-datepicker>
```
